### ISSUE TITLE
Rename safe_mode to debug_mode

### ISSUE THREAD

**Issue by yebai** [chalk-lab/Mooncake.jl#168]
It’s not obvious what safe mode is, and what limitations it induces. Let’s document that. 

EDIT: also, given the significant performance penalty of using safe mode, does it make sense to enable it by default?

**Comment by willtebbutt** [comment]
Is addressed via #175 and https://github.com/SciML/ADTypes.jl/pull/68 . Will close this when they are merged.

**Comment by willtebbutt** [comment]
This is going to stay open so that we don't forget to rename to debug mode at some point. I've let @gdalle know that we would like to do this at some point, so when a breaking change in ADTypes next happens, we'll bundle it in with that.

**Comment by willtebbutt** [comment]
There don't appear to be any breaking released -- `ADTypes` is still in version 1.x.x.

**Comment by willtebbutt** [comment]
No, 1.5 -> 1.6 is a minor (feature) release. 1.5 -> 2.0 is a major (breaking) release. See e.g. https://semver.org/ for details.

**Comment by willtebbutt** [comment]
> This is not breaking in major ways, so I won't suggest waiting for ADTypes 2.0.

This is something that you'll have to discuss with @gdalle -- I do not have control over this, and I don't view this as being sufficiently important to really push him to make a breaking release sooner rather than later.

> It also only affects Tapir's constructor AutoTapir, so if needed, we can support both constructors AutoTapir(debug_mode=false) and AutoTapir(safe_mode=false) but throw a depreciation warning for the latter.

We could potentially just add a constructor, but we can't change the name of the field from `safe_mode` to `debug_mode` (as this is breaking). My preference is to change it all, or change none of it, rather than have two things for users to look out for.

**Comment by willtebbutt** [comment]
This is definitely also true in Julia -- there have been no breaking releases since 1.0 in the public interface (or, at least, nothing intentional). What kinds of changes are you thinking about in 1.7?

**Comment by willtebbutt** [comment]
> I'm not saying these are major, but it does seem that minor breaking changes do happen from time to time, for good reasons.

Fair point.

**Comment by gdalle** [comment]
I would rather add a new keyword argument and deprecate the old one. Even though it's minor, such a change would break things e.g. for people using Tapir through DifferentiationInterface

**Comment by willtebbutt** [comment]
I've opened a PR here: https://github.com/SciML/ADTypes.jl/pull/75

It's quite ugly, which in combination with the inconsistency it introduces, makes me think we're better off waiting until ADTypes makes a breaking release to do any of this. @gdalle @yebai please let me know what you think.

**Comment by gdalle** [comment]
Honestly I think we should leave things as they are. Tapir is free to interpret the "safe mode" argument as they see fit, so the renaming is not really worth our sweat.

**Comment by gdalle** [comment]
Thats why I closed the PR. If a v2 of ADTypes ever gets discussed we can revisit this, but that could be literal years away so in the meantime let's move on

**Comment by gdalle** [comment]
Unless I'm mistaken, we did our best to ensure the changes to `AutoReverseDiff` were not breaking, by preserving the old behavior with the `compile` field.
It's not a question of package-dependent bar height, it's a question of avoiding breaking changes whenever possible. And renaming a keyword argument because you don't like how it sounds is a _very very minimal_ change, which means you can definitely live with the old kwarg name.

**Comment by gdalle** [comment]
The key difference is that your request is a purely esthetic change, which you can easily live with (whereas the ReverseDiff change had performance implications for static dispatch).
_In my view_, purely esthetic changes like this one do not justify additional code complexity in a package. ADTypes is a central package and we want to keep it as lightweight and easily maintainable as possible. Every PR is weighed on the cost/benefit tradeoff, and in your case the benefit is basically zero.

**Comment by gdalle** [comment]
The inaccurate terminology was the reason behind https://github.com/SciML/ADTypes.jl/pull/68, which in my view is a good middle ground.
For instance, if you wanted to turn safe/debug mode _off_ by default, I would definitely consider the change because it has performance benefits. But for a simple renaming, I don't think it's worth it.

**Comment by willtebbutt** [comment]
This was resolved during the renaming process :)
