### ISSUE TITLE
Type-unstable `struct` arguments

### ISSUE THREAD

**Issue by yebai** [chalk-lab/Mooncake.jl#184]
Discovered and discussed [here](https://github.com/TuringLang/AdvancedVI.jl/issues/63#issuecomment-2167594525).

**Comment by willtebbutt** [comment]
This is going to be trivial to solve once I've modified the rrule!! interface to provide the arguments passed to the rrule also to the forwards-pass of a rule to the reverse-pass (this is a performance optimisation). Since this is a fairly high-priority problem, I'm going to bump this API change up the list of things which are important, and try to get it done this week.
