### ISSUE TITLE
Add SkipOptimisation

### ISSUE THREAD

**Issue by yebai** [chalk-lab/Mooncake.jl#243]
We could optimise functions that we know won't influence gradients. Some examples from ReverseDiff: 

- [SKIPPED_UNARY_SCALAR_FUNCS](https://github.com/JuliaDiff/ReverseDiff.jl/blob/8ee3b80e70903eb22f3701ea9f2445749995f44b/src/ReverseDiff.jl#L29)
- [SKIPPED_BINARY_SCALAR_FUNCS](https://github.com/JuliaDiff/ReverseDiff.jl/blob/8ee3b80e70903eb22f3701ea9f2445749995f44b/src/ReverseDiff.jl#L30)
- [map/broadcast](https://github.com/JuliaDiff/ReverseDiff.jl/blob/8ee3b80e70903eb22f3701ea9f2445749995f44b/src/derivatives/elementwise.jl#L38)
- [SKIPPED_DIFFRULES](https://github.com/JuliaDiff/ReverseDiff.jl/blob/8ee3b80e70903eb22f3701ea9f2445749995f44b/src/ReverseDiff.jl#L34C7-L34C24)

Any others?

**Comment by willtebbutt** [comment]
We actually do this quite a bit already. See [here](https://github.com/compintell/Tapir.jl/blob/4b840467c1d1762f92b171cc5f12918c772e3d5c/src/rrules/misc.jl#L9). It might make sense for me to split this out into a separate file though, so that it's more clearly labelled, rather than just being under "misc".
